apiVersion: v1
kind: Pod
metadata:
  name: hypernet-dataset-10000
  namespace: thwalsh
spec:
  securityContext:
    runAsUser: 264391
    runAsGroup: 1132
  restartPolicy: Never
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A40
  volumes:
    - name: home-vol
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/thwalsh
        readOnly: false
    - name: local-vol
      emptyDir: {}
  containers:
    - name: hypernet-dataset-container-10000
      image: "ghcr.io/tyson-walsh/hypernets-pip-slim:v12"
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Gi"
          cpu: "8"
          nvidia.com/gpu: "2"
        limits:
          memory: "96Gi"
          cpu: "24"
          nvidia.com/gpu: "2"
      volumeMounts:
        - name: home-vol
          mountPath: /sciclone/home/thwalsh
        - name: local-vol
          mountPath: /tmp
      workingDir: /
      env:
        - name: HF_HOME
          value: "/tmp/huggingface"
        - name: HF_DATASETS_CACHE
          value: "/tmp/huggingface/datasets"
        - name: HF_MODULES_CACHE
          value: "/tmp/huggingface/modules"
        - name: HUGGINGFACE_HUB_CACHE
          value: "/tmp/huggingface/hub"
        - name: XDG_CACHE_HOME
          value: "/tmp/huggingface"
        - name: OMP_NUM_THREADS
          value: "24"
        - name: CPU_THREADS
          value: "24"
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1"
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -ex
          echo "------------------------------------------------------------"
          echo "Hypernetwork Dataset Pod started at $(date)"
          source /venv/bin/activate

          # honor CPU thread setting if provided
          if [[ -n "${CPU_THREADS}" ]]; then
            export OMP_NUM_THREADS=${CPU_THREADS}
          fi

          cd /sciclone/home/thwalsh/hypernets/data_scripts
          mkdir -p ../log_files

          echo "Running hypernetwork_feature_builder_10000.py with 2 shards..."
          python hypernetwork_feature_builder_10000.py --shards 2 --force \
            > ../log_files/hypernetwork_feature_builder_10000.log 2>&1

          echo "Hypernetwork Dataset Processing completed successfully at $(date)"
          ls -lh